import argparse
import logging
import os
import re
from typing import Dict, Tuple

import yaml

LOG = logging.getLogger("yaml_converter")
LOG.setLevel(logging.INFO)


class YamlConverter:
    """Converts YAML Schemas to proto files. Can deal with any and timestamp types."""

    def __init__(self):
        self.needed_keys = {"Description", "Type", "Unit", "Hipaa", "Pii"}
        self.enums = {}

    def get_proto_header(self, data: Dict, version: str, repo: str, file_name: str):
        """
        Creates and writes the proto header to the file handle.

        :param data:    Content of the Yaml.
        :param version: Version of the Yaml schema, will be written as the proto package.
        :repo:          Name of the bitbucket repository.
        :file_name:     File name without extension of the YAML file.
        """

        repo_name = re.sub("\\W+", "", repo)
        proto_message_name = data["Name"]
        proto_header = (
            'syntax = "proto3";\noption go_package = "go/";\n\n'
            "// ################################################# //\n"
            "// DO NOT CHANGE THIS FILE!!!\n"
            "// This proto file is autogenerated by DWH.\n"
            f"// For any changes, edit the YAML source {file_name}.yaml\n"
            "// and regeneration a new version of this proto file.\n"
            "// ################################################# //\n\n"
            f"package {repo_name}_{file_name}_{proto_message_name}_{version};\n"
            f"/* version: {version} */\n\n"
        )

        if "'Type': 'any'" in str(data):
            proto_header += 'import "google/protobuf/any.proto";\n\n'

        if "'Type': 'timestamp'" in str(data):
            proto_header += 'import "google/protobuf/timestamp.proto";\n\n'

        return proto_header

    @staticmethod
    def create_proto_entry(data_type: str, param_name: str, index: int,
                           repeated: bool = False) -> str:
        """
        Adds a new proto entry and translates incoming datatype from to protobuf. In particular, the
        following types are changed:
            - timestamp
            - int
            - any

        :param data_type:   Name of the datatype (defined in yaml).
        :param param_name:  Name of the parameter.
        :param index:       Position/Index of parameter in resulting proto file.
        :param repeated:    Flag indicating if parameter is repeated or not.

        :return: String with new proto entry.
        """
        if data_type == "timestamp":
            data_type = "google.protobuf.Timestamp"
        elif data_type == "int":
            data_type = "int64"
        elif data_type == "any":
            data_type = "google.protobuf.Any"

        if repeated:
            output = "  repeated "
        else:
            output = "  "
        return output + f"{data_type} {param_name} = {index};\n"

    @staticmethod
    def get_enum_block(enum_items: dict, name: str) -> str:
        """
        Writes a full enum block to the proto file, e.g.
            enum NAME {
                Param1 = Index1;
                Param2 = Index2;
                ...
            }

        :param enum_items:  Yaml content of enum.
        :param name:    Name of the enum.
        """
        message = f"enum {name} {{\n"
        for item_name, item_id in enum_items.items():
            message += f"  {item_name} = {item_id};\n"

        message += "};\n\n"
        return message

    def get_proto_entry(self, data: Dict, name: str, index: int) -> Tuple[int, str]:
        """
        Writes a new parameter to the proto file within a message block, e.g.
            Type ParamName = Index;

        if the input has all required fields.

        :param data:    Yaml content belonging to the parameter.
        :param name:    Name of the parameter.
        :param index:   Position of the parameter within the proto message.

        :return:
            - index:    updated position within message block
            - proto:    new proto entry (may be empty if not all required fields are present)
        """
        proto = ""
        if self.all_required_fields_existing(data):
            index += 1
            is_repeated = data.get("Mode") == "REPEATED"
            proto = self.create_proto_entry(data_type=data["Type"],
                                            param_name=name,
                                            index=index,
                                            repeated=is_repeated)
        return index, proto

    def is_record(self, data: Dict) -> bool:
        """Checks if data is a record by verifying that all elements are a valid parameter entry."""
        for value in data.values():
            if not self.all_required_fields_existing(value):
                return False
        return True

    def is_enum(self, data: Dict) -> bool:
        """Checks if data is an enum by verifying that type equals enum."""
        if data.get("Type", "").lower() == "enum" and isinstance(data.get("Enum"), dict):
            return True
        return False

    def get_message_block(self, data: Dict, name: str):
        """
        Writes a full message block to the proto file, e.g.
            message NAME {
                Type1 Param1 = Index1;
                Type2 Param2 = Index2;
                ...
            }

        :param data:    Full Yaml content.
        :param name:    Name of the message.
        """
        message = f"message {name} {{\n"
        idx = 0
        for entry in data:
            if isinstance(data[entry], dict):
                if self.is_record(data[entry]):
                    idx += 1
                    message += self.create_proto_entry(data_type=entry,
                                                       param_name=entry,
                                                       index=idx)
                elif self.is_enum(data[entry]):
                    idx += 1
                    data_type = self.check_enum_entries(name=entry, data=data[entry])
                    message += self.create_proto_entry(
                        data_type=data_type,
                        param_name=entry,
                        index=idx,
                        repeated=True if data[entry].get("Mode") == "REPEATED" else False,
                    )
                else:
                    idx, proto = self.get_proto_entry(data=data[entry], name=entry, index=idx)
                    message += proto
            elif isinstance(data[entry], list):
                idx += 1
                message += self.create_proto_entry(data_type=entry,
                                                   param_name=entry,
                                                   index=idx,
                                                   repeated=True)

        message += "};\n\n"
        return message

    def check_enum_entries(self, name: str, data: Dict) -> str:
        """
        Checks if current enum is already known to the current schema

        :param name: current parameter name which is defined as enum
        :param data: schema entry for parameter with name 'name'
        :param msg_name: name of an already known enum (previously defined in this schema)
        :param known_enums: items of the already known enum with name 'msg_name'
        :param enum_items: items of the current enum

        :class variable enums: python object with msg_name:enum_items as key:value

        returns the message name of the known enum or the current parameter name as new message name
        """
        enum_items = data.get("Enum", {})
        enum_items = {k: v for k, v in sorted(enum_items.items(), key=lambda item: item[1])}
        for msg_name, known_enums in self.enums.items():
            if enum_items == known_enums:
                return msg_name

        self.enums[name] = data.get("Enum", {})
        return name

    def get_repeated_and_record(self, data: Dict):
        """
        Wrapper of write_message_block, but for repeated and nested fields.

        :param data: Full Yaml content.
        """
        message = ""
        for entry in data:
            if isinstance(data[entry], list):
                for list_entry in data[entry]:
                    message += self.get_message_block(list_entry, entry)
            elif self.is_record(data[entry]):
                message += self.get_message_block(data[entry], entry)
        return message

    def get_enums(self) -> str:
        """
        Reads enum entries from class variable 'enums' collected during conversion

        returns a string of enums formatted in proto language
        """
        message = ""
        for msg_name, entries in self.enums.items():
            message += self.get_enum_block(enum_items=entries, name=msg_name)

        return message

    def yaml_to_proto(self, data: Dict, version: str, repo: str, file_name: str) -> str:
        """
        Converts the yaml into a proto file.

        :param data:      Full Yaml content.
        :param version:   Version of the Yaml schema, will be written as the proto package.
        :param repo:      Name of the bitbucket repository.
        :param file_name: File name without extension of the YAML file.
        """

        proto = self.get_proto_header(data, version, repo, file_name)
        proto += self.get_message_block(data["Content"], data["Name"])
        proto += self.get_repeated_and_record(data["Content"])
        proto += self.get_enums()
        return proto

    def all_required_fields_existing(self, data) -> bool:
        return isinstance(data, dict) and len(self.needed_keys & set(list(data.keys()))) == len(
            self.needed_keys)


def read_file(file_name):
    with open(file_name, "r") as f:
        return f.read().splitlines()


def load_yaml_file(file_path: str, report_file_path: str) -> Dict:
    """
    Load a YAML file from the specified path and return the content as a dictionary.
    :param file_path: Path to the YAML file
    :param report_file_path: Path to the report file
    :return: Dictionary of  the content.
    """

    with open(file_path, "r") as stream:
        try:
            return yaml.load(stream, Loader=yaml.CLoader)
        except yaml.YAMLError as e:
            with open(report_file_path, "a") as f:
                f.write(f"{file_path}: {e}")


def determine_version(original_proto_files: list, yaml_name: str) -> str:
    """
    Extracts version from previously created proto file, already present on main branch. If the
    schema is completely new, or no match is found, the default "v1" is returned.

    :param original_proto_files:    List of proto file paths present on the main branch.
    :param yaml_name:               Name of the current yaml schema.
    """
    for original_proto_file in original_proto_files:
        original_proto_file_name, old_version = os.path.split(original_proto_file)[1].split(".")[
            0].rsplit("_", 1)

        if yaml_name == original_proto_file_name:
            return f"v{int(old_version.replace('v', '')) + 1}"

    return "v1"


def convert_yaml(yaml_file: str, report_file_path: str, proto_dir: str, original_proto_files: list,
                 repo: str) -> None:
    """
    Converts a YAML file to a proto file.

    :param yaml_file: Path to the YAML file
    :param report_file_path: Path to the report file
    :param proto_dir: Path to the proto directory
    :param original_proto_files: List of proto file paths present on the main branch.
    :param repo: Name of the bitbucket repository.

    """

    yaml_name = os.path.split(yaml_file)[1].split(".")[0]
    yaml_data = load_yaml_file(yaml_file, report_file_path)

    proto_version = determine_version(original_proto_files=original_proto_files,
                                      yaml_name=yaml_name)
    proto_file_name = os.path.join(proto_dir, f"{yaml_name}_{proto_version}.proto")

    converter = YamlConverter()
    with open(proto_file_name, "w") as proto_file:
        proto_file.write(converter.yaml_to_proto(data=yaml_data, version=proto_version, repo=repo,
                                                 file_name=yaml_name))

    with open(report_file_path, "a") as report:
        report.write(
            f"successfully converted {os.path.split(yaml_file)[1]} " f"to {os.path.split(proto_file_name)[1]}\n"
        )


def main(args):
    report_file_path = os.path.join(args.report, "yaml-to-proto-report.txt")

    yaml_files = read_file(file_name=args.yaml_list)
    original_proto_files = read_file(file_name=args.original_proto_names)

    for yaml_file in yaml_files:
        convert_yaml(
            yaml_file=yaml_file,
            report_file_path=report_file_path,
            proto_dir=args.proto_dir,
            original_proto_files=original_proto_files,
            repo=args.git_repo_name,
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Read YAML files and convert to proto")
    parser.add_argument("--yaml_list", help="File including paths to all changed YAML schemas")
    parser.add_argument(
        "--original_proto_names",
        help="File including paths to all existing Proto fails on main branch"
    )
    parser.add_argument("--proto_dir", help="Absolute directory where proto schemas are stored")
    parser.add_argument("--git_repo_name",
                        help="Name of the corresponding schema bitbucket repository")
    parser.add_argument("--report", help="Absolute Path to report including failures")
    args = parser.parse_args()

    main(args)
